language: cpp
sudo: required

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get install gcc-11 g++-11
    - sudo apt-get install clang-12 clang++-12

jobs:
    include:
        -   compiler: gcc
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - cmake
                        - gcc-11
                        - g++-11
                    env:
                        - MATRIX_EVAL="CC=gcc-11 && CXX=g++-11"

        -   compiler: clang
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise-12
                    packages:
                        - cmake
                        - clang-12
                        - wget
                    env:
                        - COMPILER=clang++-12
                        - CC_COMPILER=clang-12
        -   os: osx
            osx_image: xcode12.5

before_script:
    - export CC=$CC_COMPILER
    - export CXX=$COMPILER

branches:
    - main
    - develop

script:
    - cd $TRAVIS_BUILD_DIR
    - cmake -G "Unix Makefiles" .
    - make -j 4