language: cpp
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - gcc-9
      env:
         - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

    include:
    - os: osx
      osx_image: xcode12.5

before_install:
- eval "${MATRIX_EVAL}"
- sudo apt-get install gcc-10 g++-10
- sudo apt-get install clang-1205.0.22.11 clang++-1205.0.22.11

compiler:
- gcc
- clang

branches:
  - main
  - develop

script:
- cd $TRAVIS_BUILD_DIR
- cmake -G "Unix Makefiles" .
- make -j 4