language: cpp
dist: bionic
sudo: required

compiler:
    - clang
    - gcc

jobs:
    include:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-10
          env:
              - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

        -   os: linux
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise-10
                    packages:
                        - cmake
                        - clang-10
                        - wget
            env:
                - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

        -   os: osx
            osx_image: xcode12.5

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get update
    - sudo apt-get install gcc-10 g++-10
    - sudo apt-get install clang-10 lldb-10 lld-10

branches:
    - main
    - develop

script:
    - cd $TRAVIS_BUILD_DIR
    - cmake -G "Unix Makefiles" .
    - make -j 4