language: cpp
sudo: required

matrix:
    include:
        -   os: linux
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                    packages:
                        - gcc-11
                        - g++-11
                        - cmake
            env:
                - COMPILER=g++-10
                - CC_COMPILER=gcc-10
    include:
        -   os: linux
            addons:
                apt:
                    sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise-10
                    packages:
                        - cmake
                        - clang-10
                        - wget
                        - cpputest
            env:
                - COMPILER=clang++-10
                - CC_COMPILER=clang-10

    include:
        -   os: osx
                osx_image: xcode12.5

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get install gcc-11 g++-11

before_install:
    - eval "${MATRIX_EVAL}"

compiler:
    - gcc
    - clang

branches:
    - main
    - develop

script:
    - cd $TRAVIS_BUILD_DIR
    - cmake -G "Unix Makefiles" .
    - make -j 4